/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runescape_revised_content_jni_WoodcuttingNative */

#ifndef _Included_com_runescape_revised_content_jni_WoodcuttingNative
#define _Included_com_runescape_revised_content_jni_WoodcuttingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runescape_revised_content_jni_WoodcuttingNative
 * Method:    executeWoodcutting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runescape_revised_content_jni_WoodcuttingNative_executeWoodcutting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
