/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runescape_revised_content_jni_FishingNative */

#ifndef _Included_com_runescape_revised_content_jni_FishingNative
#define _Included_com_runescape_revised_content_jni_FishingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runescape_revised_content_jni_FishingNative
 * Method:    executeFishing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runescape_revised_content_jni_FishingNative_executeFishing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
