/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runescape_revised_content_jni_RunecraftingNative */

#ifndef _Included_com_runescape_revised_content_jni_RunecraftingNative
#define _Included_com_runescape_revised_content_jni_RunecraftingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runescape_revised_content_jni_RunecraftingNative
 * Method:    executeRunecrafting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runescape_revised_content_jni_RunecraftingNative_executeRunecrafting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
