/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runescape_revised_content_jni_MiningNative */

#ifndef _Included_com_runescape_revised_content_jni_MiningNative
#define _Included_com_runescape_revised_content_jni_MiningNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runescape_revised_content_jni_MiningNative
 * Method:    executeMining
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_runescape_revised_content_jni_MiningNative_executeMining
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
