/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runescape_revised_jni_JNI */

#ifndef _Included_com_runescape_revised_jni_JNI
#define _Included_com_runescape_revised_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runescape_revised_jni_JNI
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_runescape_revised_jni_JNI_helloWorld
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
